// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "403db09b-aa79-4766-8a84-5b2a575acfd4";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onhumidChange();
void onsuhuChange();
void onledChange();

int humid;
float suhu;
bool led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(humid, READWRITE, ON_CHANGE, onhumidChange);
  ArduinoCloud.addProperty(suhu, READWRITE, ON_CHANGE, onsuhuChange);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onledChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
